export const routes = {
  home: { path: "/" as const, id: "home" as const },
  score: { path: "/score" as const, id: "score" as const },
};

export const WORDS_COUNT = 20 as const;
export const CALC_WORD_LENGTH = 5 as const;
export const CALC_MINUTE = 60 as const;
export const PUNCTUATION_CHANCE = 0.25 as const;
export const CAPITALIZE_CHANCE = 0.25 as const;
export const TIMER_SECONDS_COUNT = 30;

export const punctuationList = [".", ",", "!", "?"];

export const wordList = [
  "mix",
  "knit",
  "bleed",
  "crabs",
  "resemble",
  "baby",
  "humanly",
  "because",
  "banish",
  "cobra",
  "secure",
  "knife",
  "songs",
  "pillbox",
  "crucifix",
  "brutal",
  "verdant",
  "vibrate",
  "deduction",
  "barbaric",
  "glutton",
  "mom",
  "bright",
  "smart",
  "pathetic",
  "icicle",
  "word",
  "inflate",
  "coddle",
  "heating",
  "tooth",
  "dramatic",
  "frisky",
  "mary",
  "ditch",
  "crack",
  "lethal",
  "investment",
  "felon",
  "eliminate",
  "welcome",
  "everyday",
  "literature",
  "zephyr",
  "sawdust",
  "reading",
  "hoaxer",
  "serenity",
  "premium",
  "vessel",
  "dazzling",
  "take",
  "humid",
  "obeisant",
  "gang",
  "paltry",
  "domineering",
  "pet",
  "hibernation",
  "zany",
  "identical",
  "organize",
  "mutant",
  "step",
  "lend",
  "bronze",
  "capricious",
  "knuckle",
  "damnation",
  "cathedral",
  "encouraging",
  "aggressive",
  "heavy",
  "befall",
  "conversation",
  "bin",
  "dishonest",
  "propaganda",
  "contrast",
  "spiky",
  "virgin",
  "horses",
  "enchanted",
  "humiliate",
  "exclude",
  "crow",
  "collection",
  "use",
  "ignite",
  "constrain",
  "xenophobic",
  "woman",
  "pure",
  "environment",
  "protection",
  "piquant",
  "prophets",
  "heartbeat",
  "bluff",
  "batch",
  "auction",
  "curve",
  "blinding",
  "low",
  "hybrid",
];
